language: node_js
node_js:
  - node
addons:
  postgresql: "9.4"
before_install:
  - rvm install 2.2.3
  - gem install bundler
install:
  - npm install
before_script:
  - bundle install
  - psql -c 'create database test_travis_db;' -U postgres
  - cp ./config/database.travis.yml ./config/database.yml
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake 
