language: ruby

bundler_args: --without production

services:
  - postgresql

script: 
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake 

before_script:
  - psql -c 'create database marina_test;' -U postgres
