require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe BoatsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Boat. As you add validations to Boat, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {name: 'Topsy', description: 'Nice Boat', length: 10.6 }
  }

  let(:invalid_attributes) {
    {name: '', description: 'Nice Boat', length: 10.6 }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BoatsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all boats as @boats" do
      boat = Boat.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:boats)).to eq([boat])
    end
  end

  describe "GET #show" do
    it "assigns the requested boat as @boat" do
      boat = Boat.create! valid_attributes
      get :show, params: {id: boat.to_param}, session: valid_session
      expect(assigns(:boat)).to eq(boat)
    end
  end

  describe "GET #new" do
    it "assigns a new boat as @boat" do
      get :new, params: {}, session: valid_session
      expect(assigns(:boat)).to be_a_new(Boat)
    end
  end

  describe "GET #edit" do
    it "assigns the requested boat as @boat" do
      boat = Boat.create! valid_attributes
      get :edit, params: {id: boat.to_param}, session: valid_session
      expect(assigns(:boat)).to eq(boat)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Boat" do
        expect {
          post :create, params: {boat: valid_attributes}, session: valid_session
        }.to change(Boat, :count).by(1)
      end

      it "assigns a newly created boat as @boat" do
        post :create, params: {boat: valid_attributes}, session: valid_session
        expect(assigns(:boat)).to be_a(Boat)
        expect(assigns(:boat)).to be_persisted
      end

      it "redirects to the created boat" do
        post :create, params: {boat: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Boat.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved boat as @boat" do
        post :create, params: {boat: invalid_attributes}, session: valid_session
        expect(assigns(:boat)).to be_a_new(Boat)
      end

      it "re-renders the 'new' template" do
        post :create, params: {boat: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
         {name: 'Tapsy', description: 'Nice Big Boat', length: 100.6 }
      }

      it "updates the requested boat" do
        boat = Boat.create! valid_attributes
        put :update, params: {id: boat.to_param, boat: new_attributes}, session: valid_session
        boat.reload
        expect(boat.description).to eq('Nice Big Boat')
      end

      it "assigns the requested boat as @boat" do
        boat = Boat.create! valid_attributes
        put :update, params: {id: boat.to_param, boat: valid_attributes}, session: valid_session
        expect(assigns(:boat)).to eq(boat)
      end

      it "redirects to the boat" do
        boat = Boat.create! valid_attributes
        put :update, params: {id: boat.to_param, boat: valid_attributes}, session: valid_session
        expect(response).to redirect_to(boat)
      end
    end

    context "with invalid params" do
      it "assigns the boat as @boat" do
        boat = Boat.create! valid_attributes
        put :update, params: {id: boat.to_param, boat: invalid_attributes}, session: valid_session
        expect(assigns(:boat)).to eq(boat)
      end

      it "re-renders the 'edit' template" do
        boat = Boat.create! valid_attributes
        put :update, params: {id: boat.to_param, boat: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested boat" do
      boat = Boat.create! valid_attributes
      expect {
        delete :destroy, params: {id: boat.to_param}, session: valid_session
      }.to change(Boat, :count).by(-1)
    end

    it "redirects to the boats list" do
      boat = Boat.create! valid_attributes
      delete :destroy, params: {id: boat.to_param}, session: valid_session
      expect(response).to redirect_to(boats_url)
    end
  end

end
